docs: Add npx command for invoking Rome
romefrontend/rome pull request #1061
Opened 2020-08-13 18:43 UTC by SanketDG

## Summary

Fixes #1032

2020-08-24 08:27 UTC, ematipico requested changes
Thank you for your patience! I left some suggestion

2020-08-24 08:27 UTC, ematipico commented on website/src/_includes/docs/getting-started.md
> +This:
```suggestion
After these commands, Rome will:
```

2020-08-24 08:27 UTC, ematipico commented on website/src/_includes/docs/getting-started.md
> +- Generates project configuration which will create a `.config` directory and place a `rome.rjson` inside of it that contains your project config.
```suggestion
- execute a self-installtion by adding itself to the `package.json` as dependency of your project (if there's a `package.json` already);
- generate the configuration file inside `.config` directory. The configuration file is called `rome.rjson`.
```

2020-08-24 08:27 UTC, ematipico commented on website/src/_includes/docs/getting-started.md
> +### Installation and Quick Start
```suggestion
### Installation and quick start
```

2020-08-25 11:50 UTC, eranshapira commented on website/src/_includes/docs/getting-started.md
> +- Installs Rome locally and also adds it to `package.json`
Install*

2020-08-25 11:53 UTC, eranshapira commented on website/src/_includes/docs/getting-started.md
> +This:
> 

will -> future grammer poses an issue. this sentence should be:

`Using `npx rome init`, this is the following outcome:`

2020-08-25 11:53 UTC, eranshapira commented on website/src/_includes/docs/getting-started.md
> +- Installs Rome locally and also adds it to `package.json`
and adds* - no need for also.

2020-08-25 11:54 UTC, eranshapira commented on website/src/_includes/docs/getting-started.md
> +- Generates project configuration which will create a `.config` directory and place a `rome.rjson` inside of it that contains your project config.
Generates a project configuration which creates `.config` folder, with `rome.rjson` which serves as a project config.

2020-08-25 14:08 UTC, ematipico commented on website/src/_includes/docs/getting-started.md
> +This:
Any grammar suggestions are more than welcome! Thank you!!

2020-08-30 16:55 UTC, SanketDG commented on website/src/_includes/docs/getting-started.md
> +This:
Done!

2020-08-30 16:55 UTC, SanketDG commented on website/src/_includes/docs/getting-started.md
> +- Generates project configuration which will create a `.config` directory and place a `rome.rjson` inside of it that contains your project config.
Done

2020-08-30 16:55 UTC, SanketDG commented on website/src/_includes/docs/getting-started.md
> +### Installation and Quick Start
Done

2020-08-30 16:55 UTC, SanketDG commented on website/src/_includes/docs/getting-started.md
> +- Installs Rome locally and also adds it to `package.json`
Done

2020-08-30 20:56 UTC, sebmck commented on website/src/_includes/docs/getting-started.md
> +After running this command, Rome:
```suggestion
After running this command, Rome will:
```

2020-08-30 20:57 UTC, sebmck commented on website/src/_includes/docs/getting-started.md
> +- Iexecute a self-installation by adding itself to the `package.json` as dependency of your project (if there's a `package.json` already)
```suggestion
- Add itself to `package.json` as dependency if it wasn't present, and run your package manager to install
```

2020-08-30 20:57 UTC, sebmck commented on website/src/_includes/docs/getting-started.md
> +- Generates a project configuration which creates `.config` folder, with `rome.rjson` which serves as a project config.
```suggestion
- Generate `.config/rome.rjson` that serves as your project config.
```

2020-08-30 20:58 UTC, sebmck commented on website/src/_includes/docs/getting-started.md
> +### Installation and quickstart
```suggestion
### Installation and Usage
```

2020-09-28 12:12 UTC, ematipico approved these changes

2020-09-28 12:12 UTC, merged