feat: added lint rule noUnnecessaryContinue
romefrontend/rome pull request #1148
Opened 2020-08-25 15:44 UTC by aravind1078

## Summary

part of #976 
added lint rule nounnecessayContinue

## Test Plan
`./rome  test`

2020-08-26 08:20 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> +		console.log(4);
Come to think of it, this code is valid for this rule but it's invalid in general because `console.log(i)` will never be executed. Not sure, maybe it could be an idea for another lint rule.

2020-08-26 08:22 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.ts
> +			return path.addFixableDiagnostic(
I believe we can provide an auto fix by removing the `continue;'

2020-08-26 08:28 UTC, aravind1078 commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> +		console.log(4);
yeah, probably we could tell the user that with continue statement being present all the code below it in that block is kind of `dead code` or `non-reachable code`.

2020-08-26 10:35 UTC, ematipico requested changes
I left some suggestions around formatting. These examples will go on our website, so I think it's worth presenting them in fashion manner. Also, some documentation is missing.

I leave the final 👍  to @bitpshr

2020-08-26 10:35 UTC, ematipico commented on website/src/docs/lint/rules/js/noUnnecessaryContinue.md
> +			description: MISSING DOCUMENTATION
Description is missing, we should provide a brief explanation

2020-08-26 10:35 UTC, ematipico commented on website/src/docs/lint/rules/js/noUnnecessaryContinue.md
> +			MISSING DOCUMENTATION
Same here, we should provide a more extensive explanation of the rule

2020-08-26 10:35 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> +	}
```suggestion
	while (i) {
		if (i > 5) {
			continue;
		}
		console.log(i);
		i--;
	}
```

2020-08-26 10:35 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> +	}
```suggestion
	for (let i=0; i < 10; i++) {
    	if(i>5) {
        	console.log('sss');
        	continue;
    	}
    	else if (i >= 5 && i < 8){
        	console.log('s');
    	}
	    else {
        	console.log('dsd');
    	}
	}
```

2020-08-26 10:35 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> +	}
```suggestion
	while (condition) {
		if (conditionZ) {
			if (conditionX) {
				console.log('log');
				continue;
			}
			console.log('log');
			if (conditionY) {
				console.log('log');
			}
		}
	}
```

2020-08-26 10:35 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> +	}
```suggestion
	loop: while(1) {
		forLoop: for(let i = 0; i < 5; i++){
			if (someCondition) {
				continue loop;
			}
		}
	}
```

2020-08-26 10:35 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> +	}
```suggestion
	loop: for (let i = 0; i < 5; i++) {
		continue loop;
	}
```

2020-08-26 10:35 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> + 	continue;
```suggestion
	while (i--)
 		continue;
```

2020-08-26 10:35 UTC, ematipico commented on internal/compiler/lint/rules/js/noUnnecessaryContinue.test.rjson
> +	}
```suggestion
	while (1) {
		continue;
	}
```

2020-08-26 12:12 UTC, aravind1078 commented on website/src/docs/lint/rules/js/noUnnecessaryContinue.md
> +			description: MISSING DOCUMENTATION
@ematipico all these were auto-generated so I didn't have a look at them. can we edit these files directly or do we have to add these descriptions somewhere else so that they get populated here?

2020-08-26 12:17 UTC, ematipico commented on website/src/docs/lint/rules/js/noUnnecessaryContinue.md
> +			description: MISSING DOCUMENTATION
Yes you can edit this file directly, you need to replace the placeholder "MISSING DOCUMENTATION"

2020-08-28 01:36 UTC, sebmck commented
Nice! I think this could be simplified with the usage of the `getCompletionRecords` from `js-ast-utils`:

```
import {getCompletionRecords} from "@internal/js-ast-utils";

const {node, parent} = path;

if (node.type === "ForStatement" || ...) {
    const label = parent.type === "JSLabeledStatement" ? parent.label.name : undefined;
    for (const record of getCompletionRecords(node)) {
        if (record.type === "COMPLETION" && record.node.type === "ContinueStatement") {
            const contin = record.node;
            if (contin.label === undefined || contin.label.name === label) {
                // Unnecessary continue
            }
        }
    }
}
``

We use this helper in a bunch of places to fetch statements that cause scripts to stop terminating. I think this will also handle more cases than what's in this PR.

2020-08-28 11:50 UTC, aravind1078 commented
@sebmck am not sure if `getCompletionRecords` function will help me here because it gives all the possible completion Records which also includes valid continue statements... for example
```
while (i) {
          if (i > 5) {
		continue;
	}
	console.log(i);
	i--;
}
```
in the above scenario, the function `getCompletionRecords` gives continue as one of the completion records but, the `continue` is valid here. `getcompletionRecords` can be used to determine whether continue is the last statement in one of the paths... which is what am checking in `isContinueTheLastStatement ` function I wrote but, then again we need to check whether the continue is inside the last completion path which is the only case when `continue` is unnecessary. am not sure if we can determine whether the continue is inside the last path with the completion records we get from `getCompletionRecords`. correct me if am wrong...

2020-08-30 21:44 UTC, merged

2020-08-30 21:44 UTC, sebmck commented
Ahh right. Looks good to me then! I think there's potential here to abstract some of this logic that will be useful for other lint rules. I believe ESLint has something called a code path. Thank you!

2020-08-31 00:45 UTC, aravind1078 commented
> Ahh right. Looks good to me then! I think there's potential here to abstract some of this logic that will be useful for other lint rules. I believe ESLint has something called a code path. Thank you!

Sure i will check in eslint repo thanks!