fix: documentation and indentation for noUnnecessaryContinue in website
romefrontend/rome pull request #1164
Opened 2020-08-31 04:27 UTC by aravind1078

## Summary

documentation in website for `noUnnecessayContinue` seems to broken because of indentation, fixed it!
## Test Plan

2020-08-31 07:10 UTC, ematipico requested changes
Some wording review

2020-08-31 07:10 UTC, ematipico commented on website/src/docs/lint/rules/js/noUnnecessaryContinue.md
> +description: disallow unnecessary continue statement inside the loop
```suggestion
description: disallow unnecessary `continue` statements inside loops
```

2020-08-31 07:10 UTC, ematipico commented on website/src/docs/lint/rules/js/noUnnecessaryContinue.md
> +`continue` statement is unnecessary as the last statement inside the loop, can be safely removed
```suggestion
This rule detects `continue` statements that can be marked as unnecessary. These statements can be safely removed.
```

2020-08-31 08:49 UTC, aravind1078 commented on website/src/docs/lint/rules/index.md
> +disallow unnecessary continue statement inside the loop
```suggestion
disallow unnecessary continue `statement` inside the loop
```

2020-08-31 08:50 UTC, aravind1078 commented on website/src/docs/lint/rules/index.md
> +disallow unnecessary continue `statement` inside the loop
```suggestion
disallow unnecessary `continue` statement inside the loop
```

2020-09-27 18:00 UTC, ematipico approved these changes

2020-09-27 18:00 UTC, merged