test: add original tests for string-diff
romefrontend/rome pull request #1172
Opened 2020-09-01 09:12 UTC by JustBeYou

## Summary 
Ref #1023

2020-09-01 13:57 UTC, ematipico approved these changes

2020-09-03 12:38 UTC, darthmaim requested changes

2020-09-03 12:38 UTC, darthmaim commented on internal/string-diff/index.test.ts
> + * This tests are taken from the origianl source code and adapted
```suggestion
 * This tests are taken from the original source code and adapted
```

2020-09-04 15:28 UTC, Zenix27 approved these changes

2020-09-04 16:35 UTC, bitpshr approved these changes

2020-09-04 16:35 UTC, bitpshr commented
Thanks for this, looks great.

2020-09-04 16:35 UTC, merged